 

  
  export const videoMapping = {
    '1.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Number/1.mp4'),
    '7.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Number/7.mp4'),
    '8.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Number/8.mp4'),
    '9.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Number/9.mp4'),
    '10.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Number/10.mp4'),
    'A.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Letter/A.mp4'),
    'B.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Letter/B.mp4'),
    'C.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Letter/C.mp4'),
    'D.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Letter/D.mp4'),
    'E.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/NumberAndLetter/Letter/E.mp4'),

    'Now.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/Now.mp4'),
    'NextTime.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/NextTime.mp4'),
    'Yesterday.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/Yesterday.mp4'),
    'Today.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/Today.mp4'),
    'Tomorrow.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/Tomorrow.mp4'),
    'January.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/January.mp4'),
    'February.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/February.mp4'),
    'October.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/October.mp4'),
    'OneOClock.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/OneOClock.mp4'),
    'EveryMonday.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/TimeRelated/EveryMonday.mp4'),

    'Rain.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Rain.mp4'),
    'Ice_coldTemperature.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Ice_coldTemperature.mp4'),
    'HotTemperature_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/HotTemperature_a.mp4'),
    'Lighting.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Lighting.mp4'),
    'Rainbow_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Rainbow_a.mp4'),
    'Rainstorm_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Rainstorm_a.mp4'),
    'Sandstorm_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Sandstorm_a.mp4'),
    'Sunnyday_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Sunnyday_a.mp4'),
    'Typhoon.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/Typhoon.mp4'),
    'VolcanicEruption_a.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Weather/VolcanicEruption_a.mp4'),

    'Cat.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Cat.mp4'),
    'Cow.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Cow.mp4'),
    'Dog.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Dog.mp4'),
    'Pig.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Pig.mp4'),
    'Rat.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Rat.mp4'),
    'Chicken.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Chicken.mp4'),
    'Bird.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Bird.mp4'),
    'Fish.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Fish.mp4'),
    'Lion.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Lion.mp4'),
    'Tiger.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Animal/Tiger.mp4'),

    'Afternoon.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Afternoon.mp4'),
    'GoodAfternoon.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/GoodAfternoon.mp4'),
    'Morning.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Morning.mp4'),
    'GoodMorning.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/GoodMorning.mp4'),
    'Night.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Night.mp4'),
    'GoodNight.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/GoodNight.mp4'),
    'Sorry.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Sorry.mp4'),
    'ThankYou.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/ThankYou.mp4'),
    'Together.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Together.mp4'),
    'Meet.mp4': require('../../assets/SignLanguage_Video/DailyCommunication/Greeting/Meet.mp4'),

    'HongKong_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKong_a.mp4'),
    'HongKongCentralLibrary_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongCentralLibrary_a.mp4'),
    'HongKongCorrectionalServicesMuseum_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongCorrectionalServicesMuseum_a.mp4'),
    'HongKongCulturalCentre_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongCulturalCentre_a.mp4'),
    'HongKongFilmArchive_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongFilmArchive_a.mp4'),
    'HongKongInternationalAirport_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongInternationalAirport_a.mp4'),
    'HongKongMaritimeMuseum_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongMaritimeMuseum_a.mp4'),
    'HongKongMuseumofCoastalDefence_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongMuseumofCoastalDefence_a.mp4'),
    'HongKongMuseumofHistory_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongMuseumofHistory_a.mp4'),
    'HongKongPark_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Place/HongKongPark_a.mp4'),

    'Cake_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Cake_a.mp4'),
    'BarbecuedFood_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/BarbecuedFood_a.mp4'),
    'Satay_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Satay_a.mp4'),
    'Seafood_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Seafood_a.mp4'),
    'CreamPuff_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/CreamPuff_a.mp4'),
    'Cooked-foodStall_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Cooked-foodStall_a.mp4'),
    'FastFoodShop_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/FastFoodShop_a.mp4'),
    'FriedFood_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/FriedFood_a.mp4'),
    'Pancake_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Pancake_a.mp4'),
    'Tempura_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Food/Tempura_a.mp4'),

    'Car.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Car.mp4'),
    'Bus.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Bus.mp4'),
    'MiniBus.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/MiniBus.mp4'),
    'MTR.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/MTR.mp4'),
    'Taxi.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Taxi.mp4'),
    'Ferry.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Ferry.mp4'),
    'Aeroplane.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Aeroplane.mp4'),
    'Peaktram.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Peaktram.mp4'),
    'Train.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Train.mp4'),
    'Tram.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Transportation/Tram.mp4'),

    'BuddhasBirthday_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/BuddhasBirthday_a.mp4'),
    'ChildrensDay_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/ChildrensDay_a.mp4'),
    'ChingMingFestival_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/ChingMingFestival_a.mp4'),
    'Christmas_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/Christmas_a.mp4'),
    'ChungYeungFestival_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/ChungYeungFestival_a.mp4'),
    'DragonBoatFestival_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/DragonBoatFestival_a.mp4'),
    'Easter_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/Easter_a.mp4'),
    'FathersDay_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/FathersDay_a.mp4'),
    'MothersDay_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/MothersDay_a.mp4'),
    'Mid-AutumnFestival_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/Festival/Mid-AutumnFestival_a.mp4'),

    'Address.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/Address.mp4'),
    'HowMuch_HowMany.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/HowMuch_HowMany.mp4'),
    'Money_Dollar.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/Money_Dollar.mp4'),
    'where.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/where.mp4'),
    'Who.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/Who.mp4'),
    'Why.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/Why.mp4'),
    'How_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/How_a.mp4'),
    'Travel_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/Travel_a.mp4'),
    'TravellingSouvenir_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/TravellingSouvenir_a.mp4'),
    'IndependentTravel_a.mp4': require('../../assets/SignLanguage_Video/TravelCommunication/PhaseForTravel/IndependentTravel_a.mp4'),
   
    'Chef.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Chef.mp4'),
    'Cleaning.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Cleaning.mp4'),
    'Clerk.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Clerk.mp4'),
    'Doctor.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Doctor.mp4'),
    'Fireman.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Fireman.mp4'),
    'Nurse.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Nurse.mp4'),
    'PartTimeJob.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/PartTimeJob.mp4'),
    'PoliceOfficer.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/PoliceOfficer.mp4'),
    'Postman.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Postman.mp4'),
    'Secretary.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobOccupation/Secretary.mp4'),

    'Computer_Notebook_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Computer_Notebook_a.mp4'),
    'Double-sidedTape_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Double-sidedTape_a.mp4'),
    'Keyboard_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Keyboard_a.mp4'),
    'LetterPaper.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/LetterPaper.mp4'),
    'Note_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Note_a.mp4'),
    'Pen_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Pen_a.mp4'),
    'Pencil_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Pencil_a.mp4'),
    'Scissors_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Scissors_a.mp4'),
    'Screen_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Screen_a.mp4'),
    'Stapler_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/JobRelatedTools/Stapler_a.mp4'),

    'AirConditioner_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/AirConditioner_a.mp4'),
    'Broom_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Broom_a.mp4'),
    'CleaningProducts_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/CleaningProducts_a.mp4'),
    'Dehumidifier_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Dehumidifier_a.mp4'),
    'ExhaustFan_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/ExhaustFan_a.mp4'),
    'FaxMachine_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/FaxMachine_a.mp4'),
    'Microwave_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Microwave_a.mp4'),
    'Photocopier_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Photocopier_a.mp4'),
    'Plug_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Plug_a.mp4'),
    'Radio_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/WorkplaceEnvironment/Radio_a.mp4'),


    'Believe_Trust.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Believe_Trust.mp4'),
    'Careful.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Careful.mp4'),
    'Change.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Change.mp4'),
    'Cooperate_Cooperation.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Cooperate_Cooperation.mp4'),
    'Decide.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Decide.mp4'),
    'Decrease.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Decrease.mp4'),
    'Help.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Help.mp4'),
    'Agenda_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Agenda_a.mp4'),
    'Promote_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Promote_a.mp4'),
    'Proposal_a.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/VocabularyForMeeting/Proposal_a.mp4'),
    
    'Apply.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Apply.mp4'),
    'Boss_Employer.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Boss_Employer.mp4'),
    'Colleague.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Colleague.mp4'),
    'Dismiss.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Dismiss.mp4'),
    'Employ_Hire.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Employ_Hire.mp4'),
    'IdentityCard.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/IdentityCard.mp4'),
    'Retire.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Retire.mp4'),
    'Rest_Dayoff.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Rest_Dayoff.mp4'),
    'Resign.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Resign.mp4'),
    'Quit.mp4': require('../../assets/SignLanguage_Video/WorkplaceCommunication/Interview/Quit.mp4')



  };
